### ISSUE TITLE
All the supported format don't show in the swagger-ui

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api-service#103]
## 🐛 Describe the bug

When one goes to the swagger-ui, the list of proposed format does not match what is expected, see:

![image](https://user-images.githubusercontent.com/60993872/146833640-f31349a2-8ff9-4543-9f81-4fa95b45f848.png)

## 📜 To Reproduce
Go to the swagger-ui

http://localhost:8080/

## Expected behavior

The expected list should contain `application/kvp+json`, `text/csv` and `application/pds4+xml`

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 
Can we schedule a meeting on this please. Works for me:

![shows_json_object](https://user-images.githubusercontent.com/1130658/146835460-4bce904a-dac2-409d-b30b-b5b25a925561.png)

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

We can discuss that at the breakout tomorrow. 
But maybe I was unclear: when I start the API service, and open http://localhost:8080/ in my browser, I was thinking I can get the list of supported format (in Accept header) in the proposed menu that I shared as a screenshot but I don't see them.

Note also that when I go on the swagger editor (screenshot that you shared) I don't see the different supported formats as well. I might use a wrong version though (I tried 0.5.0-SNAPSHOT and main).

**Comment by al-niessner** [comment]
I would say the two are linked so that if we get it working in the swagger editor maybe it will be working again in your other app.

Did you do a sync to make sure you have what I have been saving (my screen shot shows 0.5.0-SNAPSHOT).

**Comment by tloubrieu-jpl** [comment]
Ok, let's do that @al-niessner , so when I go the swagger-ui, I see the same as you in the bundle section. The format of the 200 status is a reference to the object 'Counted', and this object Counted on my side does only have 3 supported formats:
![image](https://user-images.githubusercontent.com/60993872/146839318-3707e3e0-8e4b-481e-8e2c-159702ebaaa2.png)

But I see that Plural has all the expected formats. I don't know what this 'Counted' object is for, maybe it should be 'Plural' instead ?

**Comment by al-niessner** [comment]
Counted was a strange introduction back in PDS4 days. It returns nothing but the number of bundles or something like that. I did not add it, I just translated from a @tdddblog commit.

**Comment by tloubrieu-jpl** [comment]
it looks like it brings a header fields which contains the total number of record matching the request while ignoring the pagination. I believe that would make sense to have that in the Plural object and remove the Counted object.

@tdddblog do you think that will work ? 

If that is not easy to catch up with the discussion which I can understand we can discuss that at the breakout tomorrow.

**Comment by tdddblog** [comment]
I've never added Counted. I don't know what that is. Are you referring to "hits"? That's how it is called in Elasticsearch and Solr. Total number of "hits" is available in every Elasticsearch response.

**Comment by tloubrieu-jpl** [comment]
This ticket is closed per pull request [pds-api-javalib#17](https://github.com/NASA-PDS/pds-api-javalib/pull/17)
