### ISSUE TITLE
As a node operators, I want to deploy the Registry API Service with the PDS Registry.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api-service#14]
## Motivation
...so that I can access the registry using a consistent interface.

## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## Engineering Details

We need the deployment of the Registry API Service either documented as part of the Registry App or linked explicitly. These components are tightly coupled so we need to consider how to document or link to them wherever possible.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I did add 'deploy' in the title, a verb was missing in the sentence. You can change it if that is not what you had in mind.

**Comment by tloubrieu-jpl** [comment]
@tdddblog rewrote the section test your deployment.
