### ISSUE TITLE
API server crashes with OutOfMemoryError if invalid query is used

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/registry-api-service#16]
## 🐛 Describe the bug
API server crashes with OutOfMemoryError if invalid query is used

## 📜 To Reproduce
1. Go to Swagger UI (http://localhost:8080)
2. Click on 'collections' link.
3. Enter invalid query `title=Kaguya` in 'q' parameter
4. Hit 'Try it out!' button.
5. UI hangs for 20-30 seconds, then returns "Internal Server Error" 500.
6. Server logs show `java.lang.OutOfMemeory` error.

## 🕵️ Expected behavior
1. API should return error message that `=` sign is not supported in queries.
2. Server should not crash with out of memory error.

## 📚 Version of Software Used
0.1.0

## 🖥 System Info
 - OS: Windows 10
 - Browser: Firefox
 - Version: 87.0

---

** :unicorn: Applicable requirements**

**Comment by tloubrieu-jpl** [comment]
@al-niessner has rewritten the query parsing for ticket https://github.com/NASA-PDS/pds-api/issues/54. This bug need to be tested against the rewritten parsing.

**Comment by al-niessner** [comment]
With updates on [pds-api-54](https://github.com/NASA-PDS/pds-api/issues/54) and related [PR](https://github.com/NASA-PDS/registry-api-service/pull/15), no longer have OutOfMemoryError but still have a 500 because the grammar exception is not being mapped into an HTTP error code.

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams

Not any more. Parse errors are returned as HTTP errors. ANTLR interface fixed so that it does not run out of memory anymore. All work done detached for other reasons on other branches. How do we close this ticket?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl how do we want to test this out? should we have @al-niessner add a test case to prove this?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I will review Al's tickets in the afternoon

**Comment by tloubrieu-jpl** [comment]
This bug has been corrected by syntax lexer re-engineering for ticket https://github.com/NASA-PDS/pds-api/issues/54

The request now return 400 bad request
