### ISSUE TITLE
Employ budget alerts and if possible, rate/egress limits on AWS services

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api-service#21]
Don't want to be surprised by huge costs and also be aware of dollar burn rates, so put in incremental 10% budget alerts based on a $1,000/month expenditure.

Also discuss rate/egress limits w/ SAs to see if they can be put in place as well.

DSIO ticket is DSIO-257

related to NASA-PDS/cloud-initiative#1

**Comment by jordanpadams** [comment]
@jimmie have we set this up yet? Or is this tabled?

**Comment by jimmie** [comment]
rate monitoring is in place - no limits however.
