### ISSUE TITLE
Work w/ SAs to define production deployment strategy in AWS

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api-service#22]
Several items need to be worked out w/ the SA's as we approach deployment of the registry at a production level:

1. SSL certificate
2. handling of secrets such as ES user name and password, keystore password, etc
3. endpoint domain ('no new websites', and related to point #1

Other items to keep in mind:
* Need to be able to access the registry from some TBD machine
   * this wil apply to both the EN machine + some DN machines

**Comment by jordanpadams** [comment]
@jimmie should this be in the next sprint?

**Comment by jordanpadams** [comment]
Done per https://docs.google.com/presentation/d/1rLFqNvk_OfmRwmer6AdAmf2yhRnGcnXuMBYN9uWNBoc/edit?usp=sharing
