### ISSUE TITLE
As a user, I want  to get a 404 error when I attempt to request a resource which does not exists

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api-service#33]
## Motivation
...so that I request the collections of a bundle for example (/bundles/{lidvid}/collections) I know wether the bundles does not exist (404) or if it doesn't have any collection (200, empty result).

 

## Additional Details

Would apply on all crawling requests. 

## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/registry-api-service/pull/59
