### ISSUE TITLE
The end point /bundles/{lidvid}/products does not fully work

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api-service#36]
## 🐛 Describe the bug

The following line https://github.com/NASA-PDS/registry-api-service/blob/3db2bb461b74a091d4956546de7abecd5a04173e/src/main/java/gov/nasa/pds/api/engineering/controllers/MyBundlesApiController.java#L256

hard code ::P1 as part of the requested identifer of registry-refs whereas there could be multiple identifiers ::P2 ...

## 📜 To Reproduce
Request the end points /bndles/{lidvid}/products when there is more that 500 products per collection for at least one collection.

Some product will miss

## 📚 Version of Software Used

No product should miss

## 🩺 Test Data / Additional context

I am thinking it would be beneficial to leverage on the class https://github.com/NASA-PDS/registry-api-service/blob/master/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/business/CollectionProductIterator.java and mimic the behavior of class https://github.com/NASA-PDS/registry-api-service/blob/master/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/business/CollectionProductRelationships.java as BundleProductRelationships class to re-implement the method to get products of a bundle.

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/registry-api-service/pull/45

**Comment by gxtchen** [comment]
@jordanpadams @tloubrieu-jpl Do we have a collection with mutiple with more than 500 products in pds-gamma?
