### ISSUE TITLE
Implement a lid resolver

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api-service#4]
This requires to update the products/{lidvid} , collections/{lidvid}/.... controllers and use the method gov.nasa.pds.api.engineering.controllers.MyProductsApiBareController.getLatestLidVidFromLid(String) when the argument is a lid and not a lidvid.

A lidvid is lid::vid (identifier::version), so a lid is a lidvid which does not contains '::'.

**Acceptance criteria:**
Currently the following url works:
http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document::1.0

we would like the following url to also work and return the latest lidvid (with the higher version number) available in the registry:
http://localhost:8080/products/urn:nasa:pds:izenberg_pdart14_meap:document

Same for collection and bundle end points:
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube::1.0
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube
http://localhost:8080/collections/bundles/urn:nasa:pds:izenberg_pdart14_meap::1.0
http://localhost:8080/collections/bundles/urn:nasa:pds:izenberg_pdart14_meap

And their sub-url:
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube::1.0/products
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube/products
http://localhost:8080/collections/bundles/urn:nasa:pds:izenberg_pdart14_meap::1.0/collections
http://localhost:8080/collections/bundles/urn:nasa:pds:izenberg_pdart14_meap/collections

Error cases:
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube::1. --> 404 (not found), lidvid resolution case
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:: --> 404 (not found), lidvid resolution case
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube: --> 404 (not found), lid resolution
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecub --> 404 (not found since full lid is with additional e), (lid resolution)
http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap --> 404 not found is no lidvid matching urn:nasa:pds:izenberg_pdart14_meap::* exists otherwise return the lidvid record (200), lid resolution

**Comment by tloubrieu-jpl** [comment]
@al-niessner yes of course, I have added that into acceptance criteria section above.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Reviewed the code and I think I understand what is happening. Can easily make your URLs work as wanted but slight variations will not for instance `...document::1.0` works and `...document` can work but what about `...document:` or `...document::`.

This all leads to further complications with how much of the URN do you really need to know. What I mean, is can I look for this much of the livid: 'zenberg_pdart14'. The current search will not work. Maybe I just want all version 3 documents: ':document:3'. Again, the current search does not work.

The obvious angle will be that use find collections to find the larger group then sort out the lidvid one really wants. In that case you always have the exact lidvid so why bother with the latest version when missing.

Do you want me to continue with original problem or widen it to do fractional lidvid checks? The former will require further details on how much of the version can be missing like ::1 for all 1.x versions.

Lastly, when using fractional lidvid and no match occurs, the JSON back is empty or missing. Having a "no match found" response would probably be better. It indicates something was attempted and processing completed normally with no matches rather than was that an unhandled exception or something else burying a deeper issue.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

In pds4, with have lid (logical identifier) and vid (vesion identifier), the lidvid is lid::vid.

For the API we want to resolved lidivd (that already works) and lid (what you are working on).

We don't need to resolve partial lids or lids with trailing : or :: 

The ...document:  or ...document:: example should return a 400 error since they are invlid lid or lidvid.
The ...document::1 should return 404 error without updating the code that is fine.
When there is no match the error is 404 (not found), this is already implemented for lid, you'll need to extend that for lid.

Regarding the fractional lid check, we don't need to add additional resolution code since the fractional lid is can be an actual lid (which has is record in the database), so we don't want to interfere in the API with that.

Let me know if this is unclear.

Remember that there is already a method gov.nasa.pds.api.engineering.controllers.MyProductsApiBareController.getLatestLidVidFromLid(String)  to get the latest lidvid from a lid so the development should be fairly simple.

Thanks for raising the edge case for errors. I will add that to the acceptance tests.

**Comment by al-niessner** [comment]
These URLs result in a 404 error:

```
http://localhost:8080/collections/bundles/urn:nasa:pds:izenberg_pdart14_meap::1.0
http://localhost:8080/collections/bundles/urn:nasa:pds:izenberg_pdart14_meap
```

**Comment by al-niessner** [comment]
None of the error expectations are met either. Please verify the expectations are what you want and I will apply fixes. Here is the current output from the error cases:

```
niessner@elysium:~$ curl --location --request GET http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube::1.

niessner@elysium:~$ curl --location --request GET http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:
{"timestamp":1616614360392,"status":500,"error":"Internal Server Error","message":"","path":"/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:"

}niessner@elysium:~$ curl --location --request GET http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:
{"timestamp":1616614383958,"status":500,"error":"Internal Server Error","message":"","path":"/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecube:"}

niessner@elysium:~$ curl --location --request GET http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecub 
{"timestamp":1616614426105,"status":500,"error":"Internal Server Error","message":"","path":"/collections/urn:nasa:pds:izenberg_pdart14_meap:data_imagecub"}

niessner@elysium:~$ curl --location --request GET http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap 
{"id":"urn:nasa:pds:izenberg_pdart14_meap::1.0","type":"Product_Bundle","title":"Izenberg PDART 2014 MESSENGER Advanced Products Bundle","metadata":{"version":"1.0","label_url":"/var/local/harvest/archive/bundle_izenberg_pdart14_meap.xml"},"properties":{"ref_lid_instrument_host":"urn:nasa:pds:context:instrument_host:spacecraft.mess","lid":"urn:nasa:pds:izenberg_pdart14_meap","ref_lid_investigation":"urn:nasa:pds:context:investigation:mission.messenger","lidvid":"urn:nasa:pds:izenberg_pdart14_meap::1.0",...}}
niessner@elysium:~$ 
```

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner I am not sure if this is the cause of the 500 error (I did not test yet) but you need to manage the case when the method getLatestLidVidFromLid returns null (meaning no lidvid were found). That is the case where we want to raise 404 errors.

You might also update the getLatestLidVidFromLid to raise a not found exception instead of returning null.

**Comment by tloubrieu-jpl** [comment]
Note that on my version of the application (without you updates) the request curl --location --request GET 'http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap:data_eetable:' returns 404 which is what I want.

**Comment by tloubrieu-jpl** [comment]
And sorry again on that, but the lidvid and their truncation in the examples above where given as examples. The actual results depends on what you have in your local registry.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner ,

Regarding the last case, where it return 200 I think you have the correct behavior (in the 'otherwise statement'):

http://localhost:8080/collections/urn:nasa:pds:izenberg_pdart14_meap --> 404 not found is no lidvid matching urn:nasa:pds:izenberg_pdart14_meap::* exists otherwise return the lidvid record (200), lid resolution

So nothing to change on you side. Thanks
