### ISSUE TITLE
Remove Engineering from package naming

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api-service#50]
## Motivation
...so that I can feel included/welcomed in part of the development contributions. 
## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
@tloubrieu-jpl adding this towards the top of the list before we get too far into development and someone tries to extend the service

**Comment by tloubrieu-jpl** [comment]
Issue moved to [NASA-PDS/registry-api #10](https://github.com/NASA-PDS/registry-api/issues/10) via [**ZenHub**](https://www.zenhub.com/)
