### ISSUE TITLE
API unable to handle products with multiple file areas

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api-service#62]
## 🐛 Describe the bug

From @msbentley :

> And a question for Thomas following on - I ingested a few (~60) test
> products into the latest registry, and tried to make a simple product
> request, but the API service gives me:
> 
> 2021-08-20 14:20:57.335 ERROR 88586 --- [io-8080-exec-10]
> o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet
> [dispatcherServlet] in context with path [] threw exception [Request
> processing failed; nested exception is
> java.lang.IllegalArgumentException: Cannot deserialize instance of
> `java.lang.String` out of START_ARRAY token
>   at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
> gov.nasa.pds.api.engineering.elasticsearch.entities.EntityProduct["pds:File/pds:creation_date_time"])]
> with root cause
> 
> I suspect it's related to one particular product, since if I mess with
> the start/limit parameters I can work around it, but I haven't figured
> out which yet...

From @tdddblog :

> I think this is a bug in API. It could not handle products with multiple data files. For example,
```xml
<Product_XML_Schema ...
     ...........
    <File_Area_XML_Schema>
        <File>
            <file_name>PDS4_SPECLIB_1B00_1000.xsd</file_name>
            <creation_date_time>2019-11-22T13:12:14</creation_date_time>
            <file_size unit="byte">43384</file_size>
            <records>925</records>
        </File>
        <XML_Schema>
            <name>PDS4_SPECLIB_1B00_1000.xsd</name>
            <offset unit="byte">0</offset>
            <parsing_standard_id>XML Schema Version 1.1</parsing_standard_id>
            <description>This is a PDS4 XML Schema file for the declared namespace.</description>
        </XML_Schema>
    </File_Area_XML_Schema>
    <File_Area_XML_Schema>
        <File>
            <file_name>PDS4_SPECLIB_1B00_1000.sch</file_name>
            <creation_date_time>2019-11-22T13:12:14</creation_date_time>
            <file_size unit="byte">16227</file_size>
            <records>234</records>
        </File>
        <XML_Schema>
            <name>PDS4_SPECLIB_1B00_1000.sch</name>
            <offset unit="byte">0</offset>
            <parsing_standard_id>Schematron ISO/IEC 19757-3:2006</parsing_standard_id>
            <description>This is the PDS4 Schematron file for the declared namespace. Schematron provides rule-based validation for XML Schema.</description>
        </XML_Schema>
    </File_Area_XML_Schema>
</Product_XML_Schema>
```

## 🕵️ Expected behavior

API returns as expected

## 📚 Version of Software Used

v0.3.2

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/registry-api-service/pull/71

**Comment by msbentley** [comment]
Hi @jordanpadams @tloubrieu-jpl are we expecting a new build of the API service with this included? I've just grabbed the latest registry, but didn't see an API release?

**Comment by tloubrieu-jpl** [comment]
Hi @msbentley , 

That update should be available in v0.4.0 of the API, see https://github.com/NASA-PDS/registry-api-service/releases/tag/untagged-2cc0311d1a8f7b6c9ff0

You can find the deployment documentation  there https://nasa-pds.github.io/pds-registry-app/install/api-server.html
We were not able to package the API server application with the rest of the registry yet, we are working on that now. The deployment method will widely rely on docker.

Let me know if you are not observing the bug correction or if you're having other issues the API.

Thanks

**Comment by msbentley** [comment]
Thanks @tloubrieu-jpl - that link doesn't seem to work for me (404). The last tagged release I see is: https://github.com/NASA-PDS/registry-api-service/releases/tag/v0.4.0-SNAPSHOT from 11 Aug 2021 which is from before this ticket was closed.

**Comment by jordanpadams** [comment]
@msbentley apologies, the previous tag was a "draft" so it didn't appear as the latest tag. That should be updated now.

**Comment by msbentley** [comment]
Looks good, thanks  @jordanpadams
